### ISSUE TITLE
Account Deletion

### ISSUE THREAD

**Issue by BrettThePark** [etn-ccis/blui-react-native-workflows#116]
#### Describe the desired behavior
The user should have a way to request that their account be deleted.

#### Describe the current behavior
Currently, there is no way for a user to request that their account is deleted

#### Is this request related to a current issue?
NO

#### Additional Context
This will soon be a [requirement for all iOS applications that allow account creation from Apple](https://developer.apple.com/news/?id=i71db0mv)

**Comment by jeffvg** [comment]
we need to set priority on this.

**Comment by joebochill** [comment]
I'm not sure that this is something that belongs in the Auth Workflow. Account Deletion seems more like something that would go in your application settings. Something like Settings > Account > Delete My Account. It doesn't make a lot of sense to me to put a feature like this on the login/registration/other pre-authentication screens.

**Comment by daileytj** [comment]
> I'm not sure that this is something that belongs in the Auth Workflow. Account Deletion seems more like something that would go in your application settings. Something like Settings > Account > Delete My Account. It doesn't make a lot of sense to me to put a feature like this on the login/registration/other pre-authentication screens.

Should we close this?

**Comment by BrettThePark** [comment]
My thoughts for consideration:

The end goal is to provide reuseable code for common things Eaton apps need to do. In this case, I think of this library more as "account management" vs "Auth". Every Eaton app needs login, change password, account deleting, etc, etc. As with change password, just because it isn't "pre-auth" doesn't mean that perhaps the library could provide a common experience for deleting an account. The end goal is to save time when developing new applications and provide a common user experience for Eaton products. In the end, I think the primary difference is that we consider the auth workflow to really be Eaton Account management.

Due to the longevity of this ticket, we have already had to implement this in our app (not a complicated screen or anything, but something that will need to be done for every Eaton app).

**Comment by ektaghag-eaton** [comment]
This won't be the part of Auth workflow, it will be part of our future user management workflow.
