### ISSUE TITLE
Make Login Workflow accessible from the root

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-native-workflows#135]
#### Describe the desired behavior
The login workflow project should be at the top level of a repo. We can move this to the top level and rename this repo to react-native-auth-workflow or create a new repo. We currently only have one workflow so there's no need to maintain what would eventually be a monorepo if we kept adding workflows. Each new workflow can be built at the root level of its own repo moving forward.

#### Describe the current behavior
The login workflow project is nested inside of the react-native-workflows repo

#### Additional Context

This stems from an issue that Brett Park was having with needing to access branches of the repo via yarn.

These 2 pull requests should provide some additional context:
https://github.com/brightlayer-ui/react-native-workflows/pull/128
https://github.com/brightlayer-ui/react-native-workflows/pull/134

**Comment by bkarambe** [comment]
We need to make sure there no incoming links from doc-it or other places.

**Comment by ektaghag-eaton** [comment]
Will handle it in moving into the monorepo.
