### ISSUE TITLE
Workflow stepper header text is cut off in landscape view on tablet

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-native-workflows#165]
#### Describe the bug
Workflow stepper header text is cut off in landscape view on tablet

#### What is the expected behavior?
Workflow stepper header text should be fully visible in landscape view on tablet

#### What are the steps to reproduce?
1. start login workflow on a tablet
2. start registration workflow
3. observe header text and close button being cut off

#### Screenshots or links to minimum reproduction example

![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-07-29 at 10 32 09](https://user-images.githubusercontent.com/13989985/181804484-5502f6bb-f6e4-496b-962f-019bdb1ea3b0.png)

**Comment by daileytj** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/13989985/187255116-be82f86f-0a60-4eca-8a79-9ceb97b188d7.png)
This is a screenshot from a physical iPad

**Comment by jeffvg** [comment]
This is screenshot from physical iPad

<img width="975" alt="image" src="https://user-images.githubusercontent.com/37150565/187255610-dbf3a84f-c7ca-4f2e-b2d7-48db266756e3.png">

**Comment by JeffGreiner-eaton** [comment]
fixed in new architecture.
