### ISSUE TITLE
Portuguese translation on change password screen missing padding

### ISSUE THREAD

**Issue by jeffvg** [etn-ccis/blui-react-native-workflows#167]
#### Describe the bug
While testing Portuguese translation we noticed the change password instructions was missing padding around the content. This is also noticed with Chinese translations as well.
#### What is the expected behavior?
Padding to remain regardless of translation. (see screen shots)
#### What are the steps to reproduce?
1. Log in
2. select user avatar menu and select change password

#### Screenshots or links to minimum reproduction example
Portuguese
<img width="239" alt="image" src="https://user-images.githubusercontent.com/37150565/182914194-b2d2b9ae-6f92-4816-bb0f-0314ffc4dcd8.png">

Chinese
<img width="237" alt="image" src="https://user-images.githubusercontent.com/37150565/182914959-a4867b29-ec6d-4a4b-ab54-a6a1777385fb.png">

<img width="237" alt="image" src="https://user-images.githubusercontent.com/37150565/182914301-5b163020-edfc-4bf8-bbac-84572be8fbf9.png">

<img width="235" alt="image" src="https://user-images.githubusercontent.com/37150565/182915358-c5e8cc91-8f4a-49fd-a8f3-3fc0cdd2878f.png">

**Comment by JeffGreiner-eaton** [comment]
fixed in new architecture. (CLOSED ISSUE)
