### ISSUE TITLE
When ALL CAPS is enabled, an icon would appear in the text field

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#173]
#### Describe the bug

I am not sure where to report this. There should be no ALL CAPS icon inside the text field.

#### What are the steps to reproduce?
1. Go to login workflow example, run it on ios
2. self registration -> create password
3. toggle all caps on
4. Observe that there is now an all caps icon in the text field

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/8997218/185309175-60fe29ba-c1c0-420d-bf43-058c27f319f4.mov

**Comment by jeffvg** [comment]
This might be default behavior but will look in to it. @huayunh Should this be removed?

**Comment by huayunh** [comment]
Yeah it looks like it might be a default iOS behavior... oops. Never thought about that. Although it looks like the second image below is where that icon shall be placed. I don't know if this is possible to change on our side.

![image](https://user-images.githubusercontent.com/8997218/186667867-709dd9d7-d962-4c16-9d94-037149105f06.png)

**Comment by ArshdeepSingh3-eaton** [comment]
this is the default iOS behaviour the icon placement has been changed.
<img width="480" alt="Screenshot 2024-03-14 at 12 35 54 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/144440086/36bf7436-0306-4e27-9d91-d16b1737bc65">

**Comment by ektaghag-eaton** [comment]
This is the default iOS behaviour the icon placement has been changed.
