### ISSUE TITLE
Text field visibility toggle buttons should not dismiss the keyboard

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#174]
#### Describe the bug

Same as title

#### What is the expected behavior?

When I have the phone keyboard enabled and try toggling the password visibility, the keyboard shall not be dismissed (if possible), and the visibility toggle should be triggered instead.

#### What are the steps to reproduce?
1. Go to login workflow example
2. Find one page with password
3. toggle keyboard on
4. activate the password text field
5. play with toggle button

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/8997218/185634021-ac0946dd-bc21-4233-be43-59cd5d0196fb.mov

**Comment by jeffvg** [comment]
Lets verify this happens on a real device too.

**Comment by joebochill** [comment]
This is fixable by using `keyboardshouldPersistTaps={'handled'}` in the ScrollView of the WorkflowCardBody.

**Comment by ektaghag-eaton** [comment]
This issue is fixed.
https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/cdfbca4c-28f7-4ffb-a463-b83602309872
