### ISSUE TITLE
Provide UI to allow user to enter verification code manually for Forget Password

### ISSUE THREAD

**Issue by dshiverware** [etn-ccis/blui-react-native-workflows#187]
#### Describe the desired behavior

- The user should have the ability to enter the verification code manually for the Forget Password flow.

#### Describe the current behavior

- Currently, the user must open their email on the phone they are using and click the link to reset their password. There are a number of potential issues here. For one, if the user clicks the link on another device they won't be able to reset their password. Another potential issue is that if the deep link isn't configured properly, or even if the link is malformed, there will be no way for the user to reset their password. 

#### Proposed solution

- Ideally, a text input for the verification code (similar to the one found in the registration flow) should be provided after the user enters their email for the Forget Password flow.

**Comment by ishiverware** [comment]
Bumping this. Shiverware still would like to see this feature implemented for both EM Install and EV Charger Manager. Users who don't have their account email setup with their phone's email app can't use deep links and therefore can't change their password when it's been forgotten. It has come up a few times in discussion with regards to EV Charger Manager.

**Comment by ektaghag-eaton** [comment]
In the latest version all screens are customisable. @dshiverware , can you please check?

**Comment by ektaghag-eaton** [comment]
@dshiverware , We are in the process of Okta integration in our workflows, which will handle all the password-related screens. Is this issue still relevant, or shall we close it?
