### ISSUE TITLE
Use latest dependencies

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-native-workflows#195]
#### Describe the desired behavior
Use the latest dependencies where possible

#### Describe the current behavior
We are not using the latest available dependencies for every third party package

#### Is this request related to a current issue?
We recently upgraded from React Native v0.64.0 to v0.70.0. In the process of this upgrade we upgraded several other dependencies, but did not update everything due to breaking changes in some of these libraries.

#### Additional Context

Some of these packages include
"@react-navigation/drawer": "^5.12.3", - 6.5.0 is available
"@react-navigation/native": "^5.9.3", - 6.0.13 is available
"@react-navigation/stack": "^5.14.3", - 6.3.2 is available
"react-native-gesture-handler": "^1.10.3", - 2.8.0 is available
"react-native-modal": "^12.0.2", - 13.0.1 is available
"react-native-safe-area-context": "^3.2.0", - 4.4.1 is available
...etc

These will likely need updated in the CLI templates as well so be sure to check there and write an additional story if they are needed after these upgrades are made.

**Comment by JeffGreiner-eaton** [comment]
fixed in new architecture.
