### ISSUE TITLE
Fix tests: Migrate from enzyme

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-native-workflows#196]
#### Describe the desired behavior
I want to have better test coverage and migrate away from enzyme in the process. 

- Remove enzyme libraries
- Use [React Test Renderer](https://reactjs.org/docs/test-renderer.html) and [React Native Testing Library](https://callstack.github.io/react-native-testing-library/) to fix the commented out tests by replacing enzyme methods.
- Ensure that we have 75% test coverage (verify this metric during review)
#### Describe the current behavior
There are many commented out tests and we are still using enzyme despite no longer being supported.

#### Additional Context

In the migration from react-native 0.64 to 0.70 and react 16 to 18 there were a few breaking changes that required the use of an updated enzyme package, however, there is no enzyme adapter support after react 17. This resulted in many commented out tests due to not being able to use enzyme methods.

**Comment by JeffGreiner-eaton** [comment]
this is fixed in new architecture
