### ISSUE TITLE
Clean up generating type definition warnings during build

### ISSUE THREAD

**Issue by jeffvg** [etn-ccis/blui-react-native-workflows#209]
#### Describe the bug
When running examples the Generating type definition throws out terminal warnings for various items.
-  Generating type definitions with tsc
src/screens/InviteRegistrationPager.tsx:247:18 - error TS2322: Type '{ children: Element | null; key: string; onDetailsChanged: Dispatch<SetStateAction<AccountDetailInformation | null>>; onSubmit: (() => void) | undefined; }' is not assignable to type 'IntrinsicAttributes & AccountDetailsProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & AccountDetailsProps'

- src/screens/InviteRegistrationPager.tsx:272:29 - error TS2322: Type 'MutableRefObject<TextInput | undefined>' is not assignable to type 'RefObject<TextInput>'.
  Types of property 'current' are incompatible.
    Type 'TextInput | undefined' is not assignable to type 'TextInput | null'.
      Type 'undefined' is not assignable to type 'TextInput | null'
- etc...

#### What is the expected behavior?
no terminal warnings
#### What are the steps to reproduce?
1. clone repo
2. yarn start:example-ios or yarn start:example-android

#### Screenshots / Screen recording
![image](https://user-images.githubusercontent.com/37150565/208973613-62eba6ff-39f0-4f0d-9a64-19c1090c4f04.png)

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Anything else to add?
some warnings are directed towards auth-shared and might need issue logged there too

**Comment by JeffGreiner-eaton** [comment]
This is fixed per new architecture
