### ISSUE TITLE
Change password screen should not have both "x" and "cancel"

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#210]
#### Describe the bug
These two buttons from the change password screen perform the same action — take a user to the previous screen
![image](https://user-images.githubusercontent.com/8997218/209200152-5d2cd66c-f40a-445a-bb94-f27d4960303f.png)

#### What is the expected behavior?
The page on docit says that there should be only one button, https://brightlayer-ui.github.io/patterns/user-auth#forgot--change-password

The bottom "cancel" button should be removed.

Note that on the web desktop version in React / Angular, there is a cancel button on the bottom, but there were no "x" on the top.

**Comment by daileytj** [comment]
Update button should be full width of container
