### ISSUE TITLE
ChangePassword screen should not over-scroll

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-native-workflows#211]
#### Describe the desired behavior
The ChangePassword screen should not over-scroll.

#### Describe the current behavior
The ChangePassword screen is over-scrolling to the point where you can see the home screen behind it

#### Is this request related to a current issue?
This is a result of code changes [in this PR](
https://github.com/brightlayer-ui/react-native-workflows/pull/208)

#### Additional Context

https://user-images.githubusercontent.com/29152776/209340687-c23a13f3-32a0-4f2e-9a13-f12f4a36caca.mov

**Comment by ektaghag-eaton** [comment]
Issue is fixed.
https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/d734d3c2-10f0-4318-94f3-4c29bd822722
