### ISSUE TITLE
Reduce visual of resend verification email button

### ISSUE THREAD

**Issue by BrettThePark** [etn-ccis/blui-react-native-workflows#217]
#### Describe the desired feature/functionality
During the account creation flow on the screen where the user is asked to enter the verification code, the resend verification button is prominent and may be unintentionally tapped by a user. Perhaps it's visual presence should be reduced when compared to other actions such as Next. 

#### Is this request related to a current issue?
No

**Comment by daileytj** [comment]
Thanks for the report @BrettThePark. I updated this a few months ago to look like this: 
![Simulator Screen Shot - iPhone 12 - 2023-01-11 at 14 07 30](https://user-images.githubusercontent.com/13989985/211897878-76f3a4af-e238-40e2-a9bd-39ee99e17dd7.png)

Is this the screen you have? 
If not, are you on the latest version of @brightlayer-ui/react-native-auth-workflow?

**Comment by BrettThePark** [comment]
Hi Thomas, It does appear that this has been resolved in the latest versions. Closing ticket.
