### ISSUE TITLE
Font scaled view pushing instruction text out of safe area view

### ISSUE THREAD

**Issue by JeffGreiner-eaton** [etn-ccis/blui-react-native-workflows#220]
#### Describe the bug / expected behavior
When resizing font from device settings to be larger than default the instruction text on change password screen drops styling and text is not wrapped in center
#### What are the steps to reproduce?

1. clone repo
2. cd login-workflow & yarn start:example-ios
3. set font to be one higher or more than default size
4. login & go to change password
5. view the instruction text area

#### Screenshots / Screen recording
Change password screen.

![image](https://user-images.githubusercontent.com/119693939/212329079-4c810ef5-0e54-49bd-9cca-58a1b5138814.png)

self-reg screen is ok.
![image](https://user-images.githubusercontent.com/119693939/212329175-c6af55c1-02fc-4ad4-b29d-ac36f9b05c61.png)

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by daileytj** [comment]
Look at how the create account content is handled and potentially duplicate those styles for the change password view.

**Comment by ektaghag-eaton** [comment]
@ektaghag-eaton , verify and close it.

**Comment by ektaghag-eaton** [comment]
Working fine in latest versions
@JeffGreiner-eaton , @joebochill 

![Screenshot_1721202520](https://github.com/user-attachments/assets/9fbfcea3-1b1f-421c-8f6f-8516ecf17ef4)
![Screenshot_1721202503](https://github.com/user-attachments/assets/3ad94fe6-bc3a-4b62-a81c-af9660f7ae0a)
![Screenshot_1721202495](https://github.com/user-attachments/assets/0e71a343-67d4-4890-ac66-e8e5e7a9359c)
![Screenshot_1721202481](https://github.com/user-attachments/assets/30ce2bea-5525-42b0-850d-cb78448036d5)
