### ISSUE TITLE
Screen transition when clicking on the "forgot password" button

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#227]
#### Describe the bug / expected behavior

It looks like the forgot password button triggers a "sudden appearance" for the inbound transition, with a sliding out for the outbound transition; this is not observed in other clicks.

#### What are the steps to reproduce?

1. Start the login workflow demo
2. Go to the login page
3. Click on "forgot password"
4. Notice how the screen just suddenly showed up
5. Exit this forgot password workflow by clicking on the x
6. Notice how now the screen slides out
7. Explore other buttons on the page. They seem to all slide in / slide out correctly.

#### Screenshots / Screen recording

https://eaton-my.sharepoint.com/:v:/p/jeffvgreiner/EXX-oZInrOxGsM19ihtU_QEB3zhtgKLPUAMQbKc28GWU7A 

#### Anything else to add?

> I wonder if forgot password was already clicked once and dismissed so it was pre-rendered. -- Tom

**Comment by ektaghag-eaton** [comment]
Fixed here https://github.com/etn-ccis/blui-react-native-workflows/pull/513
