### ISSUE TITLE
reset password action getting two invoked times if we click on done button of keyborad

### ISSUE THREAD

**Issue by rahulvageriya** [etn-ccis/blui-react-native-workflows#247]
reset password action getting invoked times if we click on done button of keyboard , due to that user is getting two email for reset password link

**Comment by rahulvageriya** [comment]
https://user-images.githubusercontent.com/99805091/225811806-ea27714b-a85f-47c0-ab26-acd558175baa.mp4

**Comment by ektaghag-eaton** [comment]
Issue should get fixed in @brightlayer-ui/react-native-auth-workflow@6.0.0. @rahulvageriya , can you please confirm?
