### ISSUE TITLE
Pre populate text input field on Change password screen

### ISSUE THREAD

**Issue by Alfurqan-Eaton** [etn-ccis/blui-react-native-workflows#256]
#### Describe the bug / expected behavior
Pre populate ability for text input on change password screen

#### What are the steps to reproduce?
Registration screen

#### ???
No

#### Anything else to add?
This will be helpful when user entered wrong password and login failed. If user click on forget password then text input field on forget password screen can be pre populated with the login failed email.

**Comment by JeffGreiner-eaton** [comment]
This will be addressed in the new refactor of login workflow

**Comment by ektaghag-eaton** [comment]
@Alfurqan-Eaton , could you please confirm if this issue has been fixed in @brightlayer-ui/[react-native-auth-workflow@6.0.0?

**Comment by Alfurqan-Eaton** [comment]
@ektaghag-eaton 
We are still on 5.0.0, not upgraded yet to 6.0.0. I'll check with team on upgrade plan and will update.
