### ISSUE TITLE
forgot password Error

### ISSUE THREAD

**Issue by dishant-jay-happiestMinds** [etn-ccis/blui-react-native-workflows#257]
When pressing on forgot password getting below Error
 ERROR  Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in Unknown (at ResetPassword.tsx:149)
    in RCTSafeAreaView (at ResetPassword.tsx:146)

steps to reproduce
1. Go to Login Screen 
2. click on forgot password

 <Provider store={store}>
      <PersistGate loading={loader()} persistor={persistor}>
        <ThemeProvider theme={BLUIThemes.blue}>
          <SafeAreaProvider>
            <SecurityContextProvider>
              <AuthUIConfiguration>
                <AuthNavigationContainer initialState={initialState} ref={ref}>
                  <RootStackNavigator />
                </AuthNavigationContainer>
              </AuthUIConfiguration>
            </SecurityContextProvider>
          </SafeAreaProvider>
        </ThemeProvider>
      </PersistGate>
    </Provider>

https://github.com/etn-ccis/blui-react-native-workflows/assets/131661182/e7d61491-2b8d-49a2-84b8-cf05d0bf7fe4

**Comment by daileytj** [comment]
@dishant-jay-happiestMinds can you provide us with the `@brightlayer-ui/react-native-auth-workflow` package version you are using.

**Comment by joebochill** [comment]
This has already been resolved in: https://github.com/etn-ccis/blui-react-native-workflows/discussions/258
