### ISSUE TITLE
User is navigated back to verification code screen on error message on account creation screen

### ISSUE THREAD

**Issue by onkarnawghare-eaton** [etn-ccis/blui-react-native-workflows#275]
#### Describe the bug / expected behaviour
Actual result :- After message Please enter valid first name . User is navigated back to verification code screen 

Expected result:- User should be on the same screen 

#### What are the steps to reproduce?

1. Open the IOS Application/Android APP
2. Click  the sign up option on Login page 
3. Accepts terms and conditions . Click on Next
4. Create an Account screen appears . 
5. Enter the email and click on next . Enter verification code . Click on next 
6. On account details page enter invalid first name . Click on next

#### Screenshots / Screen recording

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/4c4e19fa-6ed2-402c-8889-00426df67237

**Comment by ektaghag-eaton** [comment]
<img width="942" alt="Screenshot 2023-08-31 at 6 48 41 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/799e0502-4dd0-456e-9199-7d4c5338ecfa">

**Comment by ektaghag-eaton** [comment]
Fixed in previous version 5.2.0
