### ISSUE TITLE
valid property not working as expected in custom account details

### ISSUE THREAD

**Issue by onkarnawghare-eaton** [etn-ccis/blui-react-native-workflows#276]
#### Describe the bug / expected behavior
Actual result :- Next button is enabled after entering invalid custom fields

Expected result:- Next button should disabled if invalid data entered in custom fields(We are passing valid property false if any custom field invalid)

#### What are the steps to reproduce?

1. Open the IOS/Android APP
2. Click  the sign up option on Login page 
3. Accepts terms and conditions . Click on Next
4. Create an Account screen appears . 
5. Enter the email and click on next . Enter verification code . Click on next 
6. On account details page enter invalid phone number . Click on next 

#### Screenshots / Screen recording

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/ec90a099-bff3-40af-990b-688f3ce69fe5

**Comment by ektaghag-eaton** [comment]
@onkarnawghare-eaton , could you please provide a code snippet for your custom fields and validation to reproduce the mentioned scenario?

**Comment by onkarnawghare-eaton** [comment]
> @onkarnawghare-eaton , could you please provide a code snippet for your custom fields and validation to reproduce the mentioned scenario?

`// validation checks
        let valid = true;
        if (phoneNumber !== '' && phoneNumber.length !== 10 && phoneNumberPrefix !== '') {
            valid = false;
        }

        onDetailsChanged({ country, phoneNumberPrefix, phoneNumber, multifactorAuth }, valid);`

**Comment by ektaghag-eaton** [comment]
This issue is fixed.
