### ISSUE TITLE
Keypad issue on IOS

### ISSUE THREAD

**Issue by onkarnawghare-eaton** [etn-ccis/blui-react-native-workflows#279]
#### Describe the bug / expected behavior
During entering input through keypad, it keeps on moving up and down on custom account screen, Create Account screen, Verification code screen

#### What are the steps to reproduce?

1. Open  APP
2. Click on Sign up
3. Enter Email

Issue 1 :- After entering `@eaton.c`, keypad is going and coming again on typing every character

4. Click on next 
5. Enter Verification code 

Issue 2 :- On Entering verification code at every digit keypad is going and coming again  

6. Click on next
7. Enter First Name, Last Name, Numeric input field

Issue 3:- Every digit keypad is going and coming again

#### Screenshots / Screen recording

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/f0ff1b18-4d33-4b82-b18d-ada5f52f2e47

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/53f31f7d-9c7f-4502-b20d-64f43ec4fa95

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/c0782788-8617-4917-8485-68754d9ee16c

**Comment by huayunh** [comment]
BLUI-4715

**Comment by ektaghag-eaton** [comment]
Issue is fixed in brightlayer-ui/react-native-auth-workflow@6.0.0, @onkarnawghare-eaton can you please confirm?
