### ISSUE TITLE
Verification code field should get reset after navigating back and coming on screen again

### ISSUE THREAD

**Issue by onkarnawghare-eaton** [etn-ccis/blui-react-native-workflows#280]
#### Describe the bug / expected behavior
Actual result :- Verification code is there 

Expected result :- Verification code should be reset 

#### What are the steps to reproduce?

1. Open the BLI Fiji APP
2. Click on sign up 
3. Accept EULA 
4. Enter email . Click on next
5. Enter verification code

Issue 1 :- 

1. Click on BACK 
2. Again click on next 

Actual result :- Verification code is there 

Expected result :- Verification code should be reset since a new verification code is sent on clicking on Next 

 Issue 2 :- 

1. Enter verification code
2. Click on next
3. Account detail page comes , click on back 
4. User is back to verification code page . 
5. Actual result :- Verification code is there 

Expected result :- Verification code should be reset since a older one is expired now 

#### Screenshots / Screen recording

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/d97c3c8e-a6c6-4a75-9eeb-46fcf3a64356

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/5e2e6894-98f6-41a9-88e5-89dd60e50203

**Comment by JeffGreiner-eaton** [comment]
We are planning to refactor the workflow and screens to allow for additional customized actions. We will keep this as enhancement for future work in the next quarter.
