### ISSUE TITLE
The email field on Login page has no cursor, while password field has one.

### ISSUE THREAD

**Issue by rahulvageriya** [etn-ccis/blui-react-native-workflows#281]
When we type on login page on email field , there is no cursor shown , please find attached Video for more details 

https://github.com/etn-ccis/blui-react-native-workflows/assets/99805091/927379b0-616c-4c96-9563-d30ab59cfa43

**Comment by surajeaton** [comment]
It seems fine on ios, need to check on android.

**Comment by ektaghag-eaton** [comment]
Fixed in brightlayer-ui/react-native-auth-workflow@6.0.0
https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/7eebc4a5-0426-4c32-9b2c-c3ff0bea8dbd
