### ISSUE TITLE
The "resend" button in the verification code screen must be bolded, if not underlined (plus one more)

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#288]
## Describe the bug / expected behavior

The "resend" button in the verification code screen must be bolded, if not underlined. Texts that only differ in their font colors create an accessibility issue.

## What are the steps to reproduce?

I didn't run the code myself, but I noticed this in the PR description of #287

## Screenshots / Screen recording

This is React:

<img width="525" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/9e12097d-2437-45ad-9abc-b94d551d5afa">

This is React Native, as of #287
![image](https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/99651058-61a8-4801-8c03-2f349e29b7f7)

## Suggested fix

Just use an inline style overwrite

## Anything else to add?
**Also, notice the difference in the wording** — React says "Didn't receive an email?" while React Native says "Didn't receive a code?" Design-wise I am fine with either way, but I do believe they should be consistent by default. If you can address this parity in the same PR it would be awesome.

**Comment by surajeaton** [comment]
Update the instruction text and link text to match react auth workflow.

**Comment by JeffGreiner-eaton** [comment]
fixed with https://github.com/etn-ccis/blui-react-native-workflows/pull/404
