### ISSUE TITLE
Valdidation for verify code length on Verify email screen

### ISSUE THREAD

**Issue by onkarnawghare-eaton** [etn-ccis/blui-react-native-workflows#305]
#### Describe the desired feature/functionality

1. Open the BLI Fiji APP
2. Click on sign up 
3. Accept EULA 
4. Enter email . Click on next

Issue 1 :- 

Enter <6 digits 
Actual result :- Next button becomes enabled 
Expected reust :- Next button should be enabled after entring 6 digits 
![image-2023-09-06-16-05-10-640](https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/684759bf-9bce-4583-884e-9ecb99261ffe)

Issue 2 :- 

Enter more than 6 digits 
Actual result :- User is able to enter more than 6 digits 
Expected result :- User should not be able to enter more than 6 digits 
![image-2023-09-06-16-08-40-816](https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/0f837883-b7f8-44be-895e-6b7b55b8193f)

**Comment by joebochill** [comment]
This capability is going to be added in 6.0.0

**Comment by ektaghag-eaton** [comment]
This issue has been fixed in brightlayer-ui/react-native-auth-workflow@6.0.0. @onkarnawghare-eaton , can you please confirm ?
