### ISSUE TITLE
Need close button on EULA Agreement screen

### ISSUE THREAD

**Issue by onkarnawghare-eaton** [etn-ccis/blui-react-native-workflows#306]
#### Describe the desired feature/functionality
Need close button on EULA Agreement screen as per project requirement.

1. Open the IOS Application
2. Click on SignUp option on the Login page
3. Observe the EULA agreement 

![screenshot-1](https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/39ae4ad2-a359-4589-b8d3-68dcbcd88163)

**Comment by surajeaton** [comment]
@surajeaton Verify there is a close button (X) at top of the screen.

**Comment by ektaghag-eaton** [comment]
Available in @brightlayer-ui/react-native-auth-workflow@6.0.0.
![Screenshot_1720431843](https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/a5c9bea6-91c5-405f-ad07-01728a2bcd5c)
