### ISSUE TITLE
User is getting Create an Account heading with EULA body and License Agreement heading with email field

### ISSUE THREAD

**Issue by onkarnawghare-eaton** [etn-ccis/blui-react-native-workflows#307]
#### Describe the bug / expected behavior
**Actual Result:** User is getting Create an Account heading with EULA body and License Agreement heading with email field
**Expected Result:** It should behave proper heading with body

#### What are the steps to reproduce?

1. Click on 'Sign Up' link from login screen
2. Select check box and click on Next button from License Agreement screen
3. Navigate to Create an Account screen and click on back button and click on Next button from EULA screen (do it on multiple times)

#### Screenshots / Screen recording

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/bacbd1fe-24c7-4169-8a61-a204265f981d

**Comment by huayunh** [comment]
We will be taking a look at it as part of our upcoming React Native workflow rearchitecture

**Comment by ektaghag-eaton** [comment]
This issue has been fixed in @brightlayer-ui/react-native-auth-workflow@6.0.0.
