### ISSUE TITLE
Add support for React Native ^0.72.9 and Gradle 8

### ISSUE THREAD

**Issue by ishiverware** [etn-ccis/blui-react-native-workflows#316]
#### Describe the desired feature/functionality

As part of our regular maintenance schedule, Shiverware is upgrading the dependencies of the EM Install and EV Charger Manager mobile applications. One of the big upgrades we are doing is bumping from React Native 0.70.x to React Native 0.72.x. This creates both install and runtime warnings in various Brightlayer UI packages.

These don't appear to be blockers for the time being (EM Install), but we will be moving to updating EV Charger Manager next and there may be different issues. 

Upgrading to gradle 8 required us to use a patch because of a build issue (namespace must now be moved from the AndroidManifest.xml file to the build.gradle file) in Brightlayer's `react-native-vector-icons` package.

#### Additional Context (where / how would this be used)

EM Install apps
EV Charger Manager apps

#### Is this request related to a current issue?

Build warnings and runtime issues when upgrading apps to support React Native 0.72.9.
Build error with gradle 8 (in `react-native-vector-icons`).

#### Suggested implementation details

Some other notes:
- Update react-native-webview (latest 13.6.4)
- Update react-native-safe-area-context (latest 4.8.2)
- Update i18next (latest 23.7.16)
- Error when opening self registration pager since removeEventListener is no longer supported by RN 0.72.x (TypeError: _reactNative.Linking.removeEventListener is not a function). Issue involves the useRef formerly passed to AuthNavigationContainer as needed for deep linking in React Navigation 5.x. Brightlayer will probably need to migrate to React Navigation 6.x which may involve some breaking changes. We had to update our React Navigation to 6.x to avoid the error, but we still get warnings.
- To build with gradle 8, note you’ll need to update react-native-gesture-handler from ^1.6.1 to to ^2.14.1.

Other UI notes:
- Transparent spinner overlay on iOS 17.2 device iPhone 15 overlaps header bar (not sure how long this has been happening or if it was something with our updates)
- On the "Reset password" screen (as accessed via deep link), the Reset Password screen's "X" button in the top left is in line with the time in the status bar on iPhone 15 iOS 17.2. Should be in line with title text.

**Comment by joebochill** [comment]
Thanks for the report — we are currently underway with a significant update to the Workflow package to match what we did for the React web version of the workflow last year https://github.com/etn-ccis/blui-react-workflows/blob/master/login-workflow/README.md#migrating-from-v3--v4). Part of this effort includes updating to support the latest version of react-native and the other dependencies used in the workflow.

We're expecting to have this update available around the early part of Q2. We will keep an eye on the other visual issue you reported and make sure we test those in the update as well.

**Comment by ishiverware** [comment]
Thanks for the information, we'll keep a lookout for your Q2 update.

Just thought I'd include some screenshots now that Shiverware has moved on to dependency updates for the EV Charger Manager app. I believe it was after updating to the latest React Navigation V6 that we started seeing increased UI issues with the header bar (iOS only), although it may have been another dependency. Here is an example on the EULA screen of the self-registration flow:
<img width="300" alt="Screenshot 2024-02-28 at 4 25 05 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/14927723/0fbeec77-6ad0-4e46-bfdc-4eb8e8dfe659"><img width="300" alt="Screenshot 2024-02-28 at 4 25 14 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/14927723/20eeca51-bbba-4404-ad36-fb582a1fc7a6">

**Comment by ektaghag-eaton** [comment]
This issue has been fixed in brightlayer-ui/react-native-auth-workflow@6.0.0. @ishiverware , can you confirm?
