### ISSUE TITLE
[Material Design 3 Design Audit] Tiny back arrow in the app bar

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#350]
The close icons in some other screens looked fine to me. But the back arrow feels very tiny.
<img width="892" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/16d8eae6-2215-49e8-bcf3-638d19506c07">

**Comment by huayunh** [comment]
@surajeaton when you close it, do you mind linking to which PR fixed it, or if it is a won't fix, etc

**Comment by surajeaton** [comment]
Closed by https://github.com/etn-ccis/blui-react-native-workflows/pull/347
