### ISSUE TITLE
[Material Design 3 Design Audit] distance between icon and text in the header

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#351]
<img width="901" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/143dadab-f107-4b73-8766-18d8c1c1d0b6">

**Comment by huayunh** [comment]
Move this issue under RN component library if this turns out to be a component issue.

**Comment by joebochill** [comment]
We're not using the Header component so this stays in the workflow repo.
