### ISSUE TITLE
[Material Design 3 Design Audit] Wrong fonts for the line of text with "send again" button

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#353]
<img width="652" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/168ed12d-db51-48c5-a597-233d700a0938">

**Comment by surajeaton** [comment]
Setup the example with Open Sans.

**Comment by ektaghag-eaton** [comment]
Fixed here https://github.com/etn-ccis/blui-react-native-workflows/pull/404
