### ISSUE TITLE
[Material Design 3 Design Audit] Tablet Card Style

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#354]
This thing is not ready for a design audit yet. I think it is better to leave this image here -- design and screenshot side by side. I would not worry too much about the card height.

![image](https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/dcb03272-3cdd-4d0f-8ed2-2e723d2a2cf4)

**Comment by huayunh** [comment]
In addition, all paddings highlighted here need to be 24px on tablet & desktop, and 16px on mobile. This applies to only dialog box-looking components.

![image](https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/f0d1e8cd-424c-42dc-8a7f-c1eb4adfb44e)

**Comment by joebochill** [comment]
Hey @huayunh — we were a little confused by your first graphic and what is was trying to show.

Are the key takeaways here:

- Fixing border radius of the card
- Fixing padding between header and instructions
- Fix padding as highlighted in your second graphic
- Fixing the font size on set password criteria
- Update the show/hide icon to use outlined style
- Using open sans (this is called out in a separate issue)

Did we miss anything?

**Comment by huayunh** [comment]
And card background color. I was probably using "surface container" or "surface container low"

Thanks!

**Comment by ektaghag-eaton** [comment]
Fixed [here](https://github.com/etn-ccis/blui-react-native-workflows/pull/411/)
