### ISSUE TITLE
[Material Design 3 Design Audit] iPad status bar color

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-workflows#355]
Black on dark blue is hard to read. This color might change in the dark theme.

<img width="833" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/8997218/1465aea9-21b5-4419-92b4-9b5a619156b3">

**Comment by surajeaton** [comment]
It is not picking up the background color in case of tablet.

**Comment by ektaghag-eaton** [comment]
Fixed [here](https://github.com/etn-ccis/blui-react-native-workflows/pull/388)
