### ISSUE TITLE
Eliminate WorkflowCardFinishState

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-native-workflows#365]
#### Describe the desired feature/functionality

Remove the WorkflowCardFinishState component — this is an unnecessary wrapper component that doesn't do anything useful.

#### Suggested implementation details

Move the EmptyState inline on the success screens

**Comment by ektaghag-eaton** [comment]
Fixed [here](https://github.com/etn-ccis/blui-react-native-workflows/pull/415)
