### ISSUE TITLE
Default colors in Error Manager Missing

### ISSUE THREAD

**Issue by ArshdeepSingh3-eaton** [etn-ccis/blui-react-native-workflows#369]
#### Describe the bug / expected behavior
In ErrorManager.tsx 
i do not see implementation of default font color and background color
<img width="566" alt="Screenshot 2024-02-28 at 2 55 21 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/144440086/e21378e4-7470-49e8-a0d9-2ebed1a4a40e">
And colors provided in documentation do not exist in our theme
<img width="913" alt="Screenshot 2024-02-28 at 2 56 14 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/144440086/c4501f4c-8745-4337-8af4-aa61c23a37b4">

#### What are the steps to reproduce?

1. Go to...
2. Click on...

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by joebochill** [comment]
The default colors are applied in the style object: https://github.com/etn-ccis/blui-react-native-workflows/blob/release/R31/login-workflow/src/components/Error/ErrorMessageBox.tsx#L21

Will leave this issue open to address the incorrect values in the API docs.

**Comment by ektaghag-eaton** [comment]
Fixed here https://github.com/etn-ccis/blui-react-native-workflows/pull/405
