### ISSUE TITLE
Reset the registration workflow, when Finish button on success screen is pressed

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-native-workflows#382]
#### Describe the bug / expected behavior
Because the react-native-pager-view/rect-navigation does not unmount screens, after completing the registration workflow, if you go back to the registration route, you'll be at the end (success screen) instead of the beginning.

We should manually reset the registration workflow to set it back to the beginning.

#### What are the steps to reproduce?

1. In the example, when the user goes through the Registration workflow and press Finish button on the Success Screen, it navigates to the Home screen
2. Revisit the workflow, it will display the success success

#### Screenshots / Screen recording

https://github.com/etn-ccis/blui-react-native-workflows/assets/120575281/e556eec8-fef6-4035-b5f6-044e8ab5b78c

#### Suggested fix

When the Close button is pressed on any workflow screen or the Finish button is pressed on a success screen, the workflow should be reset. We should set the initial current screen / initial screen back to the default value from props (or zero) and clear any data that has been collected in RegistrationWorkflowContext.

**Comment by ektaghag-eaton** [comment]
Fixed here https://github.com/etn-ccis/blui-react-native-workflows/pull/409
