### ISSUE TITLE
Add test IDs to registration workflow

### ISSUE THREAD

**Issue by kelseybrennan12** [etn-ccis/blui-react-native-workflows#408]
#### Describe the desired feature/functionality

It would be very helpful to have [test IDs](https://reactnative.dev/docs/view#testid) for each input field and next/back button in the registration workflow.

#### Additional Context (where / how would this be used)

We have [Detox](https://wix.github.io/Detox/) tests for the BLH mobile app for new user registration, which interacts with the BLUI registration screens. These tests are much easier to write when the components that need to be interacted with have test IDs.

**Comment by surajeaton** [comment]
@kelseybrennan12 Thanks for logging this. The changes will be available in the next release.
