### ISSUE TITLE
Password and Confirm password input values are not getting cleared when click on Close or Back button

### ISSUE THREAD

**Issue by manojleaton** [etn-ccis/blui-react-native-workflows#455]
#### What are the steps to reproduce?

1. Go to ResetPasswordScreen or ChangePasswordScreen 
2. Enter values in the password and confirm password input fields
3. Click on close button or Back button
4. Go to ResetPasswordScreen or ChangePasswordScreen, observe the input fields

#### Screenshots / Screen recording
<img width="276" alt="Screenshot 2024-04-26 at 9 06 20 AM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/130662346/19920ccb-da38-4b69-8328-3bb09afb6fff">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by ektaghag-eaton** [comment]
Fixed here https://github.com/etn-ccis/blui-react-native-workflows/pull/461
