### ISSUE TITLE
Passing onChangeText in emailTextInputProps is not getting called

### ISSUE THREAD

**Issue by manojleaton** [etn-ccis/blui-react-native-workflows#456]
#### What are the steps to reproduce?

1. Pass onChangeText in emailTextInputProps in ForgotPasswordScreen and CreateAccountScreen
2. Observe passed callback onChangeText function is not getting called

#### Screenshots / Screen recording
<img width="687" alt="Screenshot 2024-04-26 at 9 14 45 AM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/130662346/706663c0-6ac5-424c-8d7b-196d05957492">
<img width="743" alt="Screenshot 2024-04-26 at 9 14 27 AM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/130662346/56616530-4c7f-430b-92b4-6e710ef0b5c7">

#### Code snippet / Link to minimum reproduction example

```
<ForgotPasswordScreen emailTextInputProps={{ onChangeText: () => console.log('test') }} />
```
```
<CreateAccountScreen emailTextFieldProps={{ onChangeText: () => console.log('test') }} />
```

**Comment by ektaghag-eaton** [comment]
Fixed here https://github.com/etn-ccis/blui-react-native-workflows/pull/471
