### ISSUE TITLE
reset password page not opening when we click on forget password url

### ISSUE THREAD

**Issue by rahulvageriya** [etn-ccis/blui-react-native-workflows#491]
Reset password page not opening when we click on reset password click (https://resi-iot-login.eaton.com/password/reset/514333/47eb2dc8-ba47-4de8-b5d8-17e22a317238?userId=47eb2dc8-ba47-4de8-b5d8-17e22a317238)

Steps to app 
1 Open App 
2 Click on forget your password ?
3 Type email
4 Click on reset password 
5 Check email and click on reset password link(https://resi-iot-login.eaton.com/password/reset/514333/47eb2dc8-ba47-4de8-b5d8-17e22a317238?userId=47eb2dc8-ba47-4de8-b5d8-17e22a317238)

Actual result : App stay on Login page in all phone 
Expected page : It should open reset page 

   We are using  "@brightlayer-ui/react-native-auth-workflow": "5.0.0",

**Comment by surajeaton** [comment]
From Rahul:
It is working file when app was killed , this issue is coming when app was in background.
this issue is still there when app was background

**Comment by ektaghag-eaton** [comment]
@rahulvageriya , Please reopen this if this issue is still exist in latest version (6.0.0).
