### ISSUE TITLE
Can we enable Login button once user type correct password format 

### ISSUE THREAD

**Issue by rahulvageriya** [etn-ccis/blui-react-native-workflows#495]
Can we enable login button when user type correct password format ?
At this moment , the button is getting enable even if we type 1 character (find attached screen.

We may can use same password format which we used in password set up screen 
![Simulator Screenshot - iPhone 15 Pro - 2024-06-20 at 17 18 55](https://github.com/etn-ccis/blui-react-native-workflows/assets/99805091/b16e2ce3-7ba4-4ad1-ae1f-3692e9179fae)
)

**Comment by surajeaton** [comment]
Check with @joebochill

**Comment by joebochill** [comment]
What is the intended use case? On the surface I don't see much value in this change. 

A user has to type in their password to successfully log in. If they type a wrong password (whether it matches a particular format or not), the login will fail. 

If this is intended to save a user a few keystrokes in case they mistype their password I think it will end up having the opposite effect. If you assume when they mistype their password that the incorrect password doesn't match the password format (and the button is disabled), the user will have to clear the field and then retype their password (vs. just having to retype the password if they tried to login and it failed). You also lose the affordance for what's going on (there's no indication of why the login button is disabled, vs. a failed login which gives you a message that the username/password are incorrect).
